Fw 2.9.0 migration
freshdesk/elastalert pull request #16
Opened 2023-03-09 09:46 UTC by ajaywk7

## Description

## Checklist

- [ ] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [ ] I have successfully run `make test-docker` with my changes.
- [ ] I have manually tested all relevant modes of the change in this PR.
- [ ] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [ ] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments

2023-03-27 08:46 UTC, aravind-musigumpula commented on Dockerfile
> +RUN echo "coming here..."
can we remove this print statement?

2023-03-27 08:46 UTC, aravind-musigumpula commented on Dockerfile
> +RUN ls /lib/
these ls statement are required ?

2023-03-27 08:49 UTC, aravind-musigumpula commented on commands.sh
> +python -m elastalert.create_index --config /data/elastalert/config.yaml --verbose
--verbose should be removed from elastalert-create-index ?
verbose argument is not supported in old elastalert and throws an error. Is it working for new elastalert

2023-03-28 06:40 UTC, aravind-musigumpula approved these changes
LGTM

2023-03-28 10:05 UTC, RashmiRam requested changes

2023-03-28 10:05 UTC, RashmiRam commented on setup.py
> +        'apscheduler>=3.8.1.post1,<4.0',
why other dependencies are downgraded?

2023-03-28 10:05 UTC, RashmiRam commented on elastalert/alerters/alertmanager.py
> -                url = '{}/api/{}/alerts'.format(host, self.api_version)
why is this change?

2023-03-28 10:05 UTC, RashmiRam commented on elastalert/elastalert.py
> +                  five=False):
I don't see the five is being used, why this change?

2023-03-28 10:05 UTC, RashmiRam commented on elastalert/elastalert.py
> +            res = self.thread_data.current_es.msearch(body=request)
If we are removing scroll, how else we are querying again and again?

2023-03-28 10:29 UTC, ajaywk7 commented on setup.py
> +        'apscheduler>=3.8.1.post1,<4.0',
Python dependency issues were coming. these versions are what worked perfectly without issues.

2023-03-28 10:33 UTC, ajaywk7 commented on elastalert/alerters/alertmanager.py
> -                url = '{}/api/{}/alerts'.format(host, self.api_version)
This is how it was in fw_0.1.35. and all existing deployments give the whole host url, thats why

2023-03-28 10:39 UTC, ajaywk7 commented on elastalert/elastalert.py
> +                  five=False):
yes, unnecessary change, removed

2023-03-28 10:40 UTC, ajaywk7 commented on elastalert/elastalert.py
> +            res = self.thread_data.current_es.msearch(body=request)
yes. this is the first changes made on top of elastalert 0.1.35  - [commit](https://github.com/freshdesk/elastalert/commit/0ad28b0d31216e1704a10997e13ce073ee52e7d6)

2023-03-28 11:06 UTC, RashmiRam commented on elastalert/elastalert.py
> +            res = self.thread_data.current_es.msearch(body=request)
No. that was for exclusively error rate. Isn't it?

2025-09-27 23:47 UTC, closed without merging